In [3]:
import numpy as np

In [5]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [8]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [10]:
arrR=np.random.randint(0,15)
arrR

2

In [13]:
arrR = np.random.randn(5)
arrR

array([ 2.30191403, -1.64838331,  0.38948789,  0.34177772, -1.4870877 ])

In [14]:
A=np.random.randn(6)

B=np.random.randn(8)

np.add(A,B)

ValueError: operands could not be broadcast together with shapes (6,) (8,) 

In [15]:
A = np.random.randn(8)

A

B = np.random.randn(8)

B

np.add(A,B)

array([-0.0416738 ,  1.69035122,  2.38007251, -0.36276279,  0.90533126,
       -1.3011658 ,  0.3492148 , -1.23602779])

In [16]:
A

array([-0.09127003,  0.25013573,  1.09436385,  0.2952886 ,  1.88391621,
       -0.49296149,  0.68620808, -0.23160818])

In [17]:
B

array([ 0.04959623,  1.44021549,  1.28570866, -0.65805138, -0.97858495,
       -0.80820431, -0.33699328, -1.00441962])

In [18]:
A = np.arange(10)

B = np.arange(20)

A

B

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [19]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
B

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [21]:
np.maximum(A,B)

ValueError: operands could not be broadcast together with shapes (10,) (20,) 

In [22]:
B = np.random.randn(10)
B

array([-0.25296999,  0.0173183 ,  0.93450156, -0.81844024, -0.85564183,
        2.61996759,  0.03539606,  0.93649143, -0.48423575,  1.5220535 ])

In [23]:
np.maximum(A,B)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [24]:
np.minimum(A,B)

array([-0.25296999,  0.0173183 ,  0.93450156, -0.81844024, -0.85564183,
        2.61996759,  0.03539606,  0.93649143, -0.48423575,  1.5220535 ])

In [25]:
website = "https://www.youtube.com/watch?v=_EfSs6-Pxx8&list=RDjMpysHVdAe0&index=18"
import webbrowser

webbrowser.open(website)

True