In [2]:
import numpy as np

In [3]:
A= np.arange(1,10)
A

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
B=A.copy()
B

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
B[0:3]=100
B

array([100, 100, 100,   4,   5,   6,   7,   8,   9])

In [6]:
A

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
C= np.zeros((10,5))
C

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
size = C.shape[1]
C.shape

(10, 5)

In [19]:
sizeA=A.shape[0]
sizeA

9

In [25]:
for i in range(size):
   C[i]=i

In [26]:
C

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
C[[1,3,5,8]]

array([[1., 1., 1., 1., 1.],
       [3., 3., 3., 3., 3.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])