In [2]:
import numpy as np


In [3]:
l=[1,2,3]


In [4]:
l

[1, 2, 3]

In [5]:
tab=np.array(l)
tab


array([1, 2, 3])

In [6]:
tab.dtype

dtype('int32')

In [7]:
np.zeros(3)

array([0., 0., 0.])

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [9]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [15]:
np.full((3,5),9)

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [20]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
np.arange(1,6,2)

array([1, 3, 5])

In [22]:
5/2

2.5

In [24]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [25]:
arr*arr

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [26]:
arr+arr


array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [27]:
arr**9


array([[        1,       512,     19683,    262144],
       [  1953125,  10077696,  40353607, 134217728]], dtype=int32)

In [29]:
arr[0][0]

1

In [30]:
brr= [1,2,3,4]
tab=np.array(brr)

In [31]:
tab

array([1, 2, 3, 4])

In [32]:
tab[2]= 9
tab

array([1, 2, 9, 4])

In [33]:
A=np.arange(0,10)

In [34]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
B=A[:6]
B

array([0, 1, 2, 3, 4, 5])

In [36]:
B[2:6]=99
B

array([ 0,  1, 99, 99, 99, 99])

In [37]:
A

array([ 0,  1, 99, 99, 99, 99,  6,  7,  8,  9])

In [1]:
A[2:6]

NameError: name 'A' is not defined

In [2]:
A

NameError: name 'A' is not defined

In [3]:
B

NameError: name 'B' is not defined

In [4]:
A= np.range(1,10)
A

NameError: name 'np' is not defined