In [1]:
import numpy as np

In [3]:
arr = np.arange(1,5)
arr

array([1, 2, 3, 4])

In [6]:
np.save('myarray',arr) #saves arr in a file called myarray.npy

In [7]:
np.load('myarray.npy') #loads content on the file

array([1, 2, 3, 4])

In [4]:
arr2  = np.arange(6,10)


In [5]:
np.savez('myzipfile',x=arr,y=arr2) #saves one or multiple arrays in a numpy zip file, 'x' and 'y' here are indexes

In [6]:
result = np.load('myzipfile.npz') #extension used here is npz


In [7]:
result['x'] #print array with index 'x'

array([1, 2, 3, 4])

In [8]:
result['y']

array([6, 7, 8, 9])

In [18]:
np.savetxt('filetxt.txt',arr,delimiter=',')

In [19]:
txt = np.loadtxt('filetxt.txt')

In [20]:
txt

array([1., 2., 3., 4.])